// <auto-generated />
using System;
using IntershipEx.Modules.Applications.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntershipEx.Modules.Applications.Persistence.Migrations
{
    [DbContext(typeof(ApplicationsDbContext))]
    [Migration("20251111173715_INternshipInfoAdded")]
    partial class INternshipInfoAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("applications")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntershipEx.Modules.Applications.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IntershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Applications", "applications");
                });

            modelBuilder.Entity("IntershipEx.Modules.Applications.Domain.Applications.Application", b =>
                {
                    b.OwnsOne("IntershipEx.Modules.Applications.Domain.Applications.InternshipInfo", "InternshipInfo", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CompanyLocation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CompanyName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications", "applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsOne("IntershipEx.Modules.Applications.Domain.Applications.Review", "Review", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ReviewNotes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("ReviewedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications", "applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("InternshipInfo")
                        .IsRequired();

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
