// <auto-generated />
using System;
using InternshipEx.Modules.Users.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipEx.Modules.Users.Persistence.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20250910141131_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.CompanySize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxEmployees")
                        .HasColumnType("int");

                    b.Property<int?>("MinEmployees")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanySizes", "users");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CompanyLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanySizeId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanySizeId");

                    b.ToTable("Employers", "users");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Profiles", "users");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CvFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("ProfileId");

                    b.ToTable("Students", "users");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Employer", b =>
                {
                    b.HasOne("InternshipEx.Modules.Users.Domain.Entities.CompanySize", "CompanySize")
                        .WithMany()
                        .HasForeignKey("CompanySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySize");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Profile", b =>
                {
                    b.HasOne("InternshipEx.Modules.Users.Domain.Entities.Employer", "Employer")
                        .WithMany("Profiles")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Student", b =>
                {
                    b.HasOne("InternshipEx.Modules.Users.Domain.Entities.Profile", "Profile")
                        .WithOne("Student")
                        .HasForeignKey("InternshipEx.Modules.Users.Domain.Entities.Student", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Employer", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("InternshipEx.Modules.Users.Domain.Entities.Profile", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
