// <auto-generated />
using System;
using InternshipEx.Modules.Practices.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipEx.Modules.Practices.Persistence.Migrations
{
    [DbContext(typeof(PracticesDbContext))]
    [Migration("20250927131454_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("practices")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CvId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId");

                    b.ToTable("Applications", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationStatusHistories", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Industries", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployerLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("IndustryId");

                    b.ToTable("Practices", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.PracticeFavorite", b =>
                {
                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PracticeId", "StudentId");

                    b.ToTable("PracticeFavorites", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills", "practices");
                });

            modelBuilder.Entity("PracticeSkill", b =>
                {
                    b.Property<Guid>("PracticesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("PracticesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("PracticeSkills", "practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Application", b =>
                {
                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.Practice", "Practice")
                        .WithMany("Applications")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.Application", "Application")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.City", b =>
                {
                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Practice", b =>
                {
                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.City", "City")
                        .WithMany("Practices")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.Industry", "Industry")
                        .WithMany("Practices")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.PracticeFavorite", b =>
                {
                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.Practice", "Practice")
                        .WithMany("Favorites")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("PracticeSkill", b =>
                {
                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.Practice", null)
                        .WithMany()
                        .HasForeignKey("PracticesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipEx.Modules.Practices.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Application", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.City", b =>
                {
                    b.Navigation("Practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Industry", b =>
                {
                    b.Navigation("Practices");
                });

            modelBuilder.Entity("InternshipEx.Modules.Practices.Domain.Entities.Practice", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
